### ISSUE TITLE
What compression method does the app use?

### ISSUE THREAD

**Issue by hyhjcjy** [ocrespo/VNCpp#2]
It seems that there is no option for compression method.  (confused @@)
What compression method does the app use?
How does the compression level worked?

**Comment by ocrespo** [comment]
Hi,

The highest compression that the server can. The maximun level is tight compression.

**Comment by hyhjcjy** [comment]
I see, thank you :)

What can I do if I want to assign a compression method to the viewer?
There is a function HandleRFBServerMessage() in rfbproto.c, which has a switch case to choose the  rect.encoding. 
Is assigning rect.encoding=rfbEncodingRaw(or other method) the correct way to reach my goal?

If I change the rfbproto.c, how to rebuild the source code for the changes to work? Just do ndk-build ?

**Comment by ocrespo** [comment]
Hi,

Yes you can change the compression but I dont remember the function but I believe that  rect.encoding=rfbEncodingRaw is a good way.

If you change rfbproto.c or other rfb files you must rebuild libvncclient (a part of libvncserver)

For view the encoding I recommend mend x11vnc because it show you the encoding

**Comment by hyhjcjy** [comment]
Thank you! But how to rebuild libvncclient?
I try to make the Makefile in the directory VNCpp/jni/include/libvncclient
but it return this error:
make[1]: **\* No rule to make target `am--refresh'.  Stop.

**Comment by ocrespo** [comment]
Sorry for the delay.

You can find the instruction to build in http://libvncserver.sourceforge.net/

**Comment by hyhjcjy** [comment]
Sorry for my lack of knowledges. I don't know if this is correct:

I saw there are a lot of .a files included as libraries(?) in your /jni/src/Android.mk file.
So is there no source file of the compression method included but just a pre-build library of LibVncServer-0.x.x included in the VNCpp source code?

If I want to make any change of the compression method, I think I have to update the libvncclient.a file in /jni/lib.
So I make changes of files in LibVncServer, and than type "make" under the folder and expect the .a files output.
But it yields .o files or .la files instead of .a files.

What can I do then? :)

**Comment by ocrespo** [comment]
There are a lot of .a file because there are a lot of dependents libraries, but you only need libVNCServer to rebuild.

You need to rebuild libVNCServer with the instructions in http://libvncserver.sourceforge.net/ , you have to use the instructions to android.

You can't use the libVNCClient.a into VNCpp project because there aren't the library's file necessary to build. You need to rebuild LibVNCServer(Client part).

You maybe can use the others .a files into the VNCpp project to resolve the libraries dependents.

Sorry for my english and I hope that it is useful.

**Comment by hyhjcjy** [comment]
Yes, it's useful. :)

I build out libvncclient.a successfully by the following steps:

(1) download LibVncServer/LibVncClient from http://libvncserver.sourceforge.net/

(2) build for Android 
Type the following commend in terminal:
$./configure --host=arm-eabi CC=the gcc path of your toolchain CFLAGS="--sysroot=path of sysroot"

(3) $make

(4) $sudo make install

Then I can find libvncclient.a & libvncserver.a in /usr/local/lib

I will try to test the compression method then. :)
